[Scheme]
Name=Forester

ColorForeground=#a8a397
ColorBackground=#141414
TabActivityColor=#845d2b

ColorCursorForeground=#a8a397
ColorCursor=#a8a397
ColorCursorUseDefault=FALSE

ColorSelection=#a8a397
ColorSelectionBackground=#2c3632
ColorSelectionUseDefault=TRUE

ColorBold=#a8a397
ColorBoldUseDefault=FALSE

ColorPalette=#1d2021;#491915;#5f5a2f;#845d2b;#1e2c37;#52536b;#2c3632;#a8a397;#363a3c;#927572;#a1a6a0;#cdc4b8;#636c75;#9596a9;#52645d;#d8d3c7
ColorBoldIsBright=FALSE
